services:
  # BACKEND SERVICE
  - type: web
    name: macromatch-backend
    env: python
    region: virginia
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.0
      - fromGroup: macromatch-production-env
    buildFilter:
      paths:
        - backend/**

  # FRONTEND SERVICE
  - type: web
    name: macromatch-frontend
    env: node
    region: virginia
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run serve-build"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://macromatch-backend.onrender.com"
      - fromGroup: macromatch-production-env
    buildFilter:
      paths:
        - frontend/**
